default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: deploy
  password: pointer
development:
  <<: *default
  database: salsa_development
test:
  <<: *default
  database: salsa_test
production:
  <<: *default
  database: salsa_production
